import json
import base64
from datetime import datetime, timezone
from google.cloud import pubsub_v1
from google.cloud import firestore
from shared.config import (
    GCP_PROJECT,
    PUBSUB_ROUTINE,
    PUBSUB_URGENT,
    PUBSUB_EMERGENT,
    FIRESTORE_COLLECTION,
)
from shared.models import ReferralContext, UrgencyClassification, UrgencyLevel
from shared.fhir_client import create_document_reference, create_communication
from shared.dlp_client import inspect_and_deidentify

URGENCY_TOPIC_MAP = {
    UrgencyLevel.ROUTINE: PUBSUB_ROUTINE,
    UrgencyLevel.URGENT: PUBSUB_URGENT,
    UrgencyLevel.EMERGENT: PUBSUB_EMERGENT,
}


def route_and_notify(
    document: dict,
    urgency: UrgencyClassification,
    context: ReferralContext,
) -> str:
    """
    RL-6: Write DocumentReference to FHIR, route to urgency Pub/Sub topic,
    create Communication resource if EMERGENT, log audit to Firestore.
    Returns the created DocumentReference ID.
    """
    # DLP inspect on letter text before write
    letter_attachment = document.get("content", [{}])[0].get("attachment", {})
    encoded_text = letter_attachment.get("data", "")
    if encoded_text:
        decoded_text = base64.b64decode(encoded_text).decode("utf-8")
        inspected_text = inspect_and_deidentify(decoded_text)
        re_encoded = base64.b64encode(inspected_text.encode("utf-8")).decode("utf-8")
        document["content"][0]["attachment"]["data"] = re_encoded

    # Write DocumentReference to FHIR store
    created_doc = create_document_reference(document)
    document_id = created_doc.get("id", "unknown")

    # Route to urgency-appropriate Pub/Sub topic
    publisher = pubsub_v1.PublisherClient()
    topic_name = URGENCY_TOPIC_MAP[urgency.urgency]
    topic_path = publisher.topic_path(GCP_PROJECT, topic_name)

    message_data = {
        "document_reference_id": document_id,
        "service_request_id": context.service_request_id,
        "patient_id": context.patient_id,
        "specialty": context.specialty,
        "urgency": urgency.urgency.value,
        "urgency_rationale": urgency.clinical_rationale,
        "confidence": urgency.confidence,
    }

    publisher.publish(
        topic_path,
        data=json.dumps(message_data).encode("utf-8"),
    )

    # If EMERGENT: create a FHIR Communication resource to alert on-call team
    if urgency.urgency == UrgencyLevel.EMERGENT:
        now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        communication = {
            "resourceType": "Communication",
            "status": "completed",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/communication-category",
                            "code": "alert",
                            "display": "Alert",
                        }
                    ]
                }
            ],
            "subject": {"reference": f"Patient/{context.patient_id}"},
            "sent": now,
            "payload": [
                {
                    "contentString": (
                        f"EMERGENT referral generated for {context.specialty}. "
                        f"DocumentReference ID: {document_id}. "
                        f"Rationale: {urgency.clinical_rationale}"
                    )
                }
            ],
            "note": [
                {
                    "text": "Generated by Referral Letter Agent -- on-call team notification"
                }
            ],
        }
        create_communication(communication)

    # Log audit record to Firestore
    db = firestore.Client(project=GCP_PROJECT)
    audit_record = {
        "document_reference_id": document_id,
        "service_request_id": context.service_request_id,
        "patient_id": context.patient_id,
        "specialty": context.specialty,
        "urgency": urgency.urgency.value,
        "urgency_rationale": urgency.clinical_rationale,
        "confidence": urgency.confidence,
        "pubsub_topic": topic_name,
        "emergent_communication_created": urgency.urgency == UrgencyLevel.EMERGENT,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    db.collection(FIRESTORE_COLLECTION).add(audit_record)

    return document_id
